# Generated by Django 4.2.6 on 2023-11-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('rareza', models.CharField(max_length=16)),
                ('descripcion', models.CharField(max_length=256)),
                ('costo', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('rareza', models.CharField(max_length=16)),
                ('descripcion', models.CharField(max_length=256)),
                ('sanacion', models.IntegerField(default=0)),
                ('duracion', models.IntegerField(default=5)),
                ('costo', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('tipo', models.CharField(max_length=16)),
                ('aporte', models.CharField(max_length=16)),
                ('vida', models.IntegerField(default=500)),
                ('velocidad', models.IntegerField(default=300)),
            ],
        ),
    ]
